---
title: "Figure4_and_suppfig4_scripts"
author: "Sreemol Gokuladhas"
date: "23/11/2021"
output: html_document
---

## Figure 4A
```{r}

# NAFLD-candidate gene list

dg <- fread("../data/nafld_spectrum_genes", header = F)


# Read LGRN data

lgrn <- fread("../results/significant_eqtls_liver_fdr_recalculated.txt",
              header = T, sep = "\t")


# check if NAFLD-candidate genes are present in LGRN
# 
dg_in_lgrn <- lgrn %>% filter(gene %in% dg$V1) %>% 
  dplyr::select(snp, gene, log2_aFC, log2_aFC_lower, log2_aFC_upper, interaction_type) %>% 
  unique()

dg_in_lgrn_genes_list <- dg_in_lgrn %>% dplyr::select(gene) %>% unique() #13

## Plot the data
## 
lgrn_df <- data.frame(Category = c("Have eQTLs", "Have no eQTLs"),
                 count = c(13, 18))

lgrn_df_prop <- lgrn_df %>%
  mutate(prop = round((count/sum(count)), 2))

lgrn_df_prop$Category <- factor(lgrn_df_prop$Category, levels = c("Have eQTLs", "Have no eQTLs"))

#pdf("../plots/figure4a.pdf",width = 3, height = 3.5)
ggplot(lgrn_df_prop, aes(Category, prop, fill = Category)) +
  geom_bar(stat = "identity", width = 0.6) +
  scale_fill_manual(values = c("#F79520", "#808285")) +
  geom_text(aes(label=paste0("N=", count)), 
            position=position_stack(vjust=1.02), size = 3) +
  scale_y_continuous(labels = function(x) paste0(x*100, "%")) +
  theme_minimal() +
  labs(x="", y = "Proportion of the NAFLD candidate genes", fill= "")+
  theme(axis.text = element_text(size = 9),
        axis.title = element_text(size = 10),
        legend.position = "none")
#dev.off()

```

## Supplementary figure 4A
```{r}

# Read gtex cis eqtls file
# 
gtex_cis <- fread("../data/Liver.v8.signif_variant_gene_pairs_short_with_ids.txt",
                  header = T, sep = "\t")
names(gtex_cis)[4] <- "snp"

# check if NAFLD-candidate genes are present in gtex cis eqtls file
# 
dg_in_gtex_cis <- gtex_cis %>% filter(gene %in% dg$V1) %>% 
  dplyr::select(snp, gene) %>% 
  unique()

dg_in_gtex_genes_list <- dg_in_gtex_cis %>% dplyr::select(gene) %>% unique() #5

# plot the results

gtex_df <- data.frame(Category = c("Have eQTLs", "Have no eQTLs"),
                 count = c(5, 26))
gtex_df_prop <- gtex_df %>%
  mutate(prop = round((count/sum(count)), 2))

gtex_df_prop$Category <- factor(gtex_df_prop$Category, levels = c("Have eQTLs", "Have no eQTLs"))

#pdf("../plots/supfig4a.pdf",width = 3, height = 3.5)
ggplot(gtex_df_prop, aes(Category, prop, fill = Category)) +
  geom_bar(stat = "identity", width = 0.6) +
  scale_fill_manual(values = c("#F79520", "#808285")) +
  geom_text(aes(label=paste0("N=", count)), 
            position=position_stack(vjust=1.02), size = 3) +
  scale_y_continuous(labels = function(x) paste0(x*100, "%")) +
  theme_minimal() +
  labs(x="", y = "Proportion of disease-associated genes", fill= "")+
  theme(axis.text = element_text(size = 9),
        axis.title = element_text(size = 10),
        legend.position = "none")
#dev.off()
```

## Figure 4B
```{r}

## Probabilty of finding random gene (all gencode genes) ocurance in the codes3d liver network
## source code location: ../scripts/test_random_gene_occurance_in_liver_codes3d.py
## 

# plot the results


rand <- read.delim("../results/random_gene_occurance_values_codes3d.txt", header = T)

#pdf("../plots/figure4b.pdf", width = 5, height = 4)
ggplot(data=rand, aes(overlaps)) + 
  geom_vline(data=rand, aes(xintercept = 13), colour="black", linetype="dashed") +
  geom_histogram(breaks=seq(0, 15, by=0.99), 
               col="red",
               fill="orange",
               alpha = .2,
               bins=5) +
  scale_x_continuous(name = "Count of random genes identified within the LGRN", expand = c(0.02,0), 
                     limits = c(0,15),
                     breaks = seq(0,15,by = 1)) +
  scale_y_continuous(name = "Frequency", expand = c(0.02,0), limits = c(0,2200),
                     breaks= seq(0,2200, by = 200)) +
  theme_bw()+
  theme(panel.background = element_blank(),
        panel.grid = element_blank())
#dev.off()

```

## Supplementary figure 4B
```{r}

# Plot the results for gtex overlaps

rand_gtex <- read.delim("../results/random_gene_occurance_values_gtex.txt", header = T)

#pdf("../plots/supfig4b.pdf", width = 5, height = 4)
ggplot(data=rand_gtex, aes(overlaps)) + 
  geom_vline(data=rand_gtex, aes(xintercept = 5), colour="black", linetype="dashed") +
  geom_histogram(breaks=seq(0, 13, by=0.99), 
               col="red",
               fill="orange",
               alpha = .2,
               bins=5) +
  scale_x_continuous(name = "Count of random genes identified within GTEx liver regulatory map", 
                     expand = c(0.02,0), 
                     limits = c(0,13),
                     breaks = seq(0,13,by = 1)) +
  scale_y_continuous(name = "Frequency", expand = c(0.02,0), limits = c(0,2500),
                     breaks= seq(0,2500, by = 200)) +
  theme_bw()+
  theme(panel.background = element_blank(),
        panel.grid = element_blank())
#dev.off()
```

